export const catalog = [{
    name: 'Гольф длинный рукав',
    model: '8-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "cream-rose",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "freesia",
      "gray",
      "khaki",
      "light-powder",
      "lilac",
      "mustard",
      "olive",
      "pale-rose",
      "powder",
      "red",
      "sand",
      "turquoise",
      "white",
    ],
    price: 125,
    size: 'S'
  },
  {
    name: 'Гольф длинный рукав',
    model: 'P8-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "cream-rose",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "freesia",
      "gray",
      "khaki",
      "light-powder",
      "lilac",
      "mustard",
      "olive",
      "pale-rose",
      "powder",
      "red",
      "sand",
      "turquoise",
      "white",
    ],
    price: 135,
    size: 'M'
  },
  {
    name: 'Гольф длинный рукав',
    model: '2P8-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "cream-rose",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "freesia",
      "gray",
      "khaki",
      "light-powder",
      "lilac",
      "mustard",
      "olive",
      "pale-rose",
      "powder",
      "red",
      "sand",
      "turquoise",
      "white",
    ],
    price: 145,
    size: 'L'
  },
  {
    name: 'Гольф длинный рукав',
    model: '3P8-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "cream-rose",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "freesia",
      "gray",
      "khaki",
      "light-powder",
      "lilac",
      "mustard",
      "olive",
      "pale-rose",
      "powder",
      "red",
      "sand",
      "turquoise",
      "white",
    ],
    price: 155,
    size: 'XL'
  },
  {
    name: 'Лодка длинный рукав',
    model: '148-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "gray",
      "jeans",
      "khaki",
      "light-cappuccino",
      "mustard",
      "olive",
      "powder",
      "red",
      "white",
    ],
    price: 125,
    size: "S"
  },
  {
    name: 'Лодка длинный рукав',
    model: 'P148-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "gray",
      "jeans",
      "khaki",
      "light-cappuccino",
      "mustard",
      "olive",
      "powder",
      "red",
      "white",
    ],
    price: 135,
    size: 'M'
  },
  {
    name: 'Лодка длинный рукав',
    model: '2P148-3',
    text: 'Котон 70% кожа 30%',
    season: 'Осень/Весна',
    colors: [
      "beet",
      "beige",
      "black",
      "blue",
      "bordeaux",
      "brown",
      "cream",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "gray",
      "jeans",
      "khaki",
      "light-cappuccino",
      "mustard",
      "olive",
      "powder",
      "red",
      "white",
    ],
    price: 145,
    size: 'L'
  },
  {
    name: 'Гольф отворот',
    model: '80-3',
    text: 'Котон 70% кожа 30%',
    season: 'Зима',
    colors: [
      "beet",
      "beige",
      "black",
      "brick",
      "bordeaux",
      "brown",
      "coral",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "gray",
      "khaki",
      "mustard",
      "pale-rose",
      "powder",
      "raspberries",
      "red",
      "white",
    ],
    price: 135,
    size: 'S'
  },
  {
    name: 'Гольф отворот',
    model: 'P80-3',
    text: 'Котон 70% кожа 30%',
    season: 'Зима',
    colors: [
      "beet",
      "beige",
      "black",
      "brick",
      "bordeaux",
      "brown",
      "coral",
      "dark-beige",
      "dark-blue",
      "dark-cappuccino",
      "dark-gray",
      "dark-green",
      "electric",
      "gray",
      "khaki",
      "mustard",
      "pale-rose",
      "powder",
      "raspberries",
      "red",
      "white",
    ],
    price: 145,
    size: 'M'
  },
]